### ISSUE TITLE
Dissapearing Textures

### ISSUE THREAD

**Issue by schimi2k** [mikesilvo164/skin.aeon.madnox#1]
Just to test this issues area, and to be Complete ;)

the "known" Textures dissapearing Problem is still here, and even worse than in Jarvis.
at least it can be forced now ( mostly move first to music, than movies-movie info )

if this couldnt be fixed - i would say: madnox wont be official released for Krypton... but i have faith and i hope team kodi will change something, or our MAGIC MIKES will find a solution

i am still at changing the collordiffuse lines... but i realy dont think this will be the ultimate fix... even when some of those changes helps with some textures

**Comment by bartolomesoriano** [comment]
@mikesilvo164 @MadMikeDoc Given the fix in Kodi provided by Ronie (which I hope makes it into a Krypton nightly soon!), can we close this ticket and resume other work to make MadNox Krypton ready?

**Comment by MadMikeDoc** [comment]
Yup, closed now due to issue found in kodi but only resolved in a test buiid so far.
