### ISSUE TITLE
Problems with long movie titles in Shelf3D View

### ISSUE THREAD

**Issue by bartolomesoriano** [mikesilvo164/skin.aeon.madnox#11]
http://forum.kodi.tv/showthread.php?tid=230821&pid=2439338#pid2439338
1. In the Shelf3D view, if the title of the film is too long, it is displayed in a single line. This creates a giant column that is really ugly, and it persists until you focus on that movie. Any long title breaks the space of the poster, and makes it "stick out" of the box, which also looks bad. IMHO, for such long titles, it should just cut off at some point instead of having three rows of text?

**Comment by mikesilvo164** [comment]
Closing to only have new issues.  Please make a new one if this is still a problem.

Thanks.
