### ISSUE TITLE
Problems with music extra info panels when using mouse

### ISSUE THREAD

**Issue by bartolomesoriano** [mikesilvo164/skin.aeon.madnox#13]
http://forum.kodi.tv/showthread.php?tid=230821&pid=2439338#pid2439338
1. When I am playing music, the extra info panels react badly to the mouse, they pop up very frequently and look bad. If I don't move the mouse at all, the panels work nicely, but it's a tough habit to break.

**Comment by mikesilvo164** [comment]
Closing to only have new issues.  Please make a new one if this is still a problem.

Thanks.
