### ISSUE TITLE
Boxset Info incomplete in 3D View

### ISSUE THREAD

**Issue by bartolomesoriano** [mikesilvo164/skin.aeon.madnox#14]
http://forum.kodi.tv/showthread.php?tid=230821&pid=2439414#pid2439414

2nd : Whenever I pass over a boxset the info displayed on top stops changing 

[Image: boxset_zps5qf4lzix.jpg]

**Comment by mikesilvo164** [comment]
This sounds like a Skin Helper issue.

**Comment by bartolomesoriano** [comment]
@MadMikeDoc since you could not replicate this issue (I could not either), should we go ahead and close it?

**Comment by bartolomesoriano** [comment]
@MadMikeDoc I will close this issue based on the user writing that it is gone after updating to latest skin.info.service script.
