### ISSUE TITLE
Remaining Krypton work

### ISSUE THREAD

**Issue by MadMikeDoc** [mikesilvo164/skin.aeon.madnox#16]
List of main thing still outstanding for the Krypton branch:

Music ratings - Done including user ratings for music as well
Anything PVR related
AddonBrowser - Done
DialogMusicInfo is only partially done - possibly done
DialogGameControllers
GlobalSearch - Done & updated InfoDialog
DialogAudioDSPManager
What's new and screenshots in DialogAddonInfo
assets in addon.xml
DialogPlayerProcessInfo

Plus stuff from last couple of pages of the thread

**Comment by mikesilvo164** [comment]
Closing to only have new issues.  Please make a new one if this is still a problem.

Thanks.
