### ISSUE TITLE
Missing Music Categories

### ISSUE THREAD

**Issue by jeneral** [mikesilvo164/skin.aeon.madnox#21]
Using a Music library, when selecting Music from the main menu only 10 items are listed. After entering any of the other categories (Artists, Albums, Genres, etc...) and going back, the 4 missing categories appear (Music Videos, Playlists, Files and Music Add-ons). If you return to the main menu and then back to music, they disappear again until you repeat the process above. 

This issue was present on the Jarvis release but I had hoped it was fixed on the Krypton release.

![screenshot001](https://cloud.githubusercontent.com/assets/357676/21812739/e6826730-d721-11e6-9aff-7da5ccbaf3ab.png)
![screenshot002](https://cloud.githubusercontent.com/assets/357676/21812738/e6811af6-d721-11e6-9f99-e439fc5a17c9.png)

**Comment by mikesilvo164** [comment]
Closing to only have new issues.  Please make a new one if this is still a problem.

Thanks.
