### ISSUE TITLE
Image Resource Integration - Leia Branch

### ISSUE THREAD

**Issue by mistervee** [mikesilvo164/skin.aeon.madnox#24]
Something to think about though is the studio/record label logos. Possibly madnox has more than what the kodi repo version does? Could be worth checking and doing a PR for those.

It is also worth checking things like the weather and language flag packs. Some of these may already be on the kodi repo.

**Image packs Required**

- resource.images.skinbackgrounds
- resource.images.skinicons - there are a lot in the extras folder might need some trimming down these are for the home screen menu
- resource.images.musicgenreicons.text - in kodi repo have submitted pull request for additional icons
- resource.images.musicgenrefanart
- ~~resource.images.moviegenreicons~~
        https://github.com/mistervee/resource.images.moviegenreicons.madnox-coloured
        https://github.com/mistervee/resource.images.moviegenreicons.madnox-bw
- resource.images.moviegenrefanart
- ~~resource.images.weatherfanart~~ - not required in kodi repo
- ~~resource.images.weathericons~~ - not required in kodi repo
- resource.images.languageflags
- resource.images.mediaflags - No one has done this in the repo, can be a first. Could also make packs for aeon nox silvo? @mikesilvo164 

**Code Updated**

- resource.images.skinbackgrounds
- resource.images.skinicons
- resource.images.musicgenreicons
- resource.images.musicgenrefanart
- ~~resource.images.moviegenreicons~~
- resource.images.moviegenrefanart
- resource.images.weatherfanart
- resource.images.weathericons
- resource.images.languageflags
- resource.images.mediaflags

**Comment by mistervee** [comment]
@mikesilvo164 @bartolomesoriano @meowmoo @MadMikeDoc 

Issue opened to track the progress.

**Comment by MadMikeDoc** [comment]
Hi,

Thanks for this, got your 'madnox' organization request but just keep getting page 404 even when logged in?

Mike

**Comment by mistervee** [comment]
@MadMikeDoc 
Still figuring out permissions, so i deleted the group. Gave you access to the movie genre icons packs.

Not sure what to put in for the in the addon.xml besides that they are complete.

**Comment by bartolomesoriano** [comment]
@mistervee, @MadMikeDoc I tested briefly yesterday in Leia and the movie genre icons resources work just fine.  I am not seeing any media flags in any views (default or colored), but I will test further to provide more details.

**Comment by MadMikeDoc** [comment]
@mistervee , check the top section of the addon.xml and the <import></import> I would think we'll need to put entries in there to automatically download the resources but no idea what we actually put as the resources aren't in kodi repo (Yet?)

Will check access and let you know.

**Comment by mistervee** [comment]
@bartolomesoriano 

The media flags are still working for me. I haven't coded anything for the media flags unless i made an error with the starts with ends with update.

@MadMikeDoc 

Atm it will need to be a manual download. I did push some updates to the official repo for the music genre icons as a test. The rest will follow over the coming weeks.

For the addon.xml in the movie genre's the summary, description and provider name are what i am not sure of. Who should be given credit for the images? Is it Schimi or did he add to some one else work?

**Comment by MadMikeDoc** [comment]
@bartolomesoriano, was this path issue with the settings clicked to show hidden files / folders in Kodi's general settings?

**Comment by bartolomesoriano** [comment]
@MadMikeDoc My bad, this setting is off by default in Leia.

**Comment by mikesilvo164** [comment]
Closing to only have new issues.  Please make a new one if this is still a problem.

Thanks.
