### ISSUE TITLE
Fix In-Progress TV Shows submenu action

### ISSUE THREAD

**Issue by bartolomesoriano** [mikesilvo164/skin.aeon.madnox#6]
The action for the In-Progress TV Shows submenu doesn't work, it takes you to the Videos menu.  Could you change the action for this submenu to ActivateWindow(Videos, videodb://inprogresstvshows/,return)? This does work and takes you to your in-progress shows.  I don't know why the current action does not work, since it points to a video node xml which is supposed to do the same thing as the action I am suggesting.

**Comment by MadMikeDoc** [comment]
Thanks Bart, will be in 15/10 Krypton update
