### ISSUE TITLE
Change window name for Oscars and Top 250 main menu items

### ISSUE THREAD

**Issue by bartolomesoriano** [mikesilvo164/skin.aeon.madnox#7]
The action for these two main menu items in the mainmenu.DATA.xml file in the skin's shortcuts directory has Videolibrary instead of Videos for the window name.  This should be changed so that it works correctly in Krypton.  Thanks.

**Comment by MadMikeDoc** [comment]
Thanks Bart, will be in 15/10 Krypton update. The old method seemed to work for me though?
